### ISSUE TITLE
Tracy panel is not working (Nette 2.4 and PHP 7.0)

### ISSUE THREAD

**Issue by vojtamares** [o2ps/WebpackNetteAdapter#6]
Hello, 
I have decided to start using webpack in my project, for now seem to be working but the debugger panel is not working, instead of panel a standart tracy error was displayed inside of tracy debugger panel.

The error message:
```
Error: Oops\NetteWebpackAdapter\Debugging\WebpackPanel
ParseError: syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in C:\Users\acast\Documents\DDM\ddm_web\vendor\oops\webpack-nette-adapter\src\Debugging\templates\WebpackPanel.panel.phtml:74
Stack trace:
#0 C:\Users\acast\Documents\DDM\ddm_web\vendor\tracy\tracy\src\Tracy\Bar.php(159): Oops\WebpackNetteAdapter\Debugging\WebpackPanel->getPanel()
#1 C:\Users\acast\Documents\DDM\ddm_web\vendor\tracy\tracy\src\Tracy\Bar.php(108): Tracy\Bar->renderPanels()
#2 C:\Users\acast\Documents\DDM\ddm_web\vendor\tracy\tracy\src\Tracy\Debugger.php(266): Tracy\Bar->render()
#3 [internal function]: Tracy\Debugger::shutdownHandler()
#4 {main}
```

There were no any other information in log/exception.log, php error.log or apache error.log.

**Comment by jiripudil** [comment]
Hello, thanks for the report, that's a bug. The template uses PHP 7.1 syntax

**Comment by jiripudil** [comment]
I've fixed this, but please consider upgrading to PHP 7.1 as 7.0 will lose active support in a month.

**Comment by vojtamares** [comment]
@jiripudil upgrade to 7.1 is on the way - I just need to upgrade it on all my devices... :D

Thank you for the fix.
